ZCS-11425 Configure LDAP attributes for storing S3 configurations
Zimbra/zm-mailbox pull request #1280
Opened 2022-06-07 09:28 UTC by inpati

**Problem Statement**
Add LDAP attributes to store S3 configurations

**Solution**
Added New Attributes:
1. globalExternalStoreConfig -> global level
2. serverExternalStoreConfig -> server level

2022-06-07 10:04 UTC, deepakzimb reviewed
This PR should contain other files as well that creates after getter/setter commands

2022-06-07 11:10 UTC, dasiyogesh commented on store/conf/attrs/zimbra-attrs.xml
> +<attr id="5000" name="globalExternalStoreConfig" type="string" cardinality="single" optionalIn="globalConfig" since="9.1.0">
there should be just one attribute which can have global as well server value
Please  refer https://github.com/Zimbra/zm-mailbox/blob/develop/store/conf/attrs/zimbra-attrs.xml#L9898

2022-06-07 11:11 UTC, dasiyogesh requested changes
globalExternalStoreConfig & serverExternalStoreConfig there should be just one attribute externalStoreConfig that can be set on global & server both

2022-06-08 04:41 UTC, deepakzimb commented on store/src/java/com/zimbra/cs/account/ZAttrServer.java
> +        if (attrs == null) attrs = new HashMap<String,Object>();
Yes Rakesh, when we run getter/setter commands, related method generates

2022-06-08 05:25 UTC, inpati commented on store/src/java/com/zimbra/cs/account/ZAttrServer.java
> +        if (attrs == null) attrs = new HashMap<String,Object>();
We can't adjust indentation in auto generated code

2022-06-08 05:26 UTC, inpati commented
> This PR should contain other files as well that creates after getter/setter commands

Added other files as well

2022-06-08 09:03 UTC, closed without merging