PREAPPS-7285 Remove powerpaste feature
Zimbra/zm-mailbox pull request #1484
Opened 2023-05-11 18:42 UTC by silentsakky

2023-05-15 08:01 UTC, sitaram-mulik-synacor approved these changes

2023-05-15 08:12 UTC, miteshsavani810 approved these changes

2023-05-23 10:06 UTC, zimsuchitgupta requested changes
Please execute 'ant generate-getters'.

2023-05-23 11:02 UTC, silentsakky commented
> Please execute 'ant generate-getters'.

Done

2023-05-23 11:06 UTC, zimsuchitgupta approved these changes

2023-05-24 09:21 UTC, merged